[package]
name = "badpiggies-cryptor-cli"
version = "0.3.3"
edition = "2021"
authors = ["ed1th"]
description = "Bad Piggies user data cryptor"
categories = ["command-line-utilities"]
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/LambdaEd1th/badpiggies-cryptor-cli"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = { version = "0.8.4" }
sha1 = { version = "0.10.6" }
cbc = { version = "0.1.2", features = ["std"] }
pbkdf2 = { version = "0.12.2", features = ["hmac"] }
clap = { version = "4.5.17", features = ["derive", "help"] }
rust-embed = { version = "8.5.0", features = ["compression"] }
